MODEL:
  META_ARCHITECTURE: ARCH_RENORM #ARCH_RENORM  # ARCH_RN_ONLY
  BASELINE: False
  
  BACKBONE:
    NAME: build_renorm_backbone
    NORM: BN
    DEPTH: 50x
    LAST_STRIDE: 1
    FEAT_DIM: 2048
    WITH_IBN: False
    PRETRAIN: True
    PRETRAIN_PATH: "/home/nr_2022/resnet50-19c8e357.pth" 
    #resnet50-19c8e357.pth
  HEADS:
    NAME: EmbeddingHead
    NORM: BN
    WITH_BNNECK: True
    POOL_LAYER: gempool
    NECK_FEAT: before
    CLS_LAYER: linear

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss")

    CE:
      EPSILON: 0.1
      SCALE: 1.

    TRI_RN:
      MARGIN: 0.5 
      NORM_FEAT: False
      # MARGIN: 0.05  
      # NORM_FEAT: True

    TRI_EN:
      MARGIN: 1.
      NORM_FEAT: False
      # MARGIN: 0.075  
      # NORM_FEAT: True

INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]

  REA:              
   ENABLED: False
   PROB: 0.5

  DO_PAD: True  

  CJ:              
    ENABLED: True
    PROB: 0.5
    BRIGHTNESS: 0.15
    CONTRAST: 0.1
    SATURATION: 0.
    HUE: 0.

  DO_AUTOAUG: True
  AUTOAUG_PROB: 0.1

  DO_FLIP: True
  FLIP_PROB: 0.5


DATALOADER:
  PK_SAMPLER: True
  NAIVE_WAY: False   
  NUM_INSTANCE: 4  
  NUM_WORKERS: 8



SOLVER:
  FP16_ENABLED: False
  OPT: Adam
  MAX_EPOCH: 120  
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1. 
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  
  IMS_PER_BATCH: 64

  SCHED: MultiStepLR
  STEPS: [30, 60, 100]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01 
  WARMUP_EPOCHS: 10
  WARMUP_METHOD: "linear"

  CHECKPOINT_PERIOD: 1

  ITERS: 1000  ### (Protocol-2) 2000 for CUHK03 & Market1501 1000 for MSMT17
  # ITERS: 800  #(Protocol-1) 1600 for CUHK03 & Market1501 800 for MSMT17

DATASETS: 
  NAMES: ("cuhkSYSU", "CUHK03All", "Market1501All", )  # (Protocol-3) leave one out "Market1501All", "cuhkSYSU", "MSMT17All", "CUHK03ALL"
  # NAMES: ("cuhkSYSU", "Market1501", "CUHK03", )  # Protocol-2 leave one out "Market1501", "cuhkSYSU", "MSMT17", "CUHK03"
  
  TESTS: ("MSMT17", )  # "Market1501", "MSMT17", "CUHK03"

OUTPUT_DIR: logs/All2C3_ReNorm

# DATASETS: 
#   NAMES: ("cuhkSYSU", "Market1501", "CUHK03", )  # Protocol-2 leave one out "Market1501", "cuhkSYSU", "MSMT17", "CUHK03"
  
#   TESTS: ("MSMT17", )  # "Market1501", "MSMT17", "CUHK03"

# OUTPUT_DIR: logs/2C3_ReNorm

TEST:
  EVAL_PERIOD: 1
  IMS_PER_BATCH: 256
  FLIP_ENABLED: True

CUDNN_BENCHMARK: True
